### ISSUE TITLE
Using "false" as a variable name is not recommended

### ISSUE THREAD

**Issue by msoos** [marijnheule/drat-trim#11]
This interferes with most modern IDEs (as they expect the system to build with C++ as well), making it nearly impossible to understand or improve the code.

**Comment by marijnheule** [comment]
renamed false to falseA

**Comment by msoos** [comment]
Thanks!

Note that I also filed a pretty serious bug about the binary DRAT
detection. It could impact the SAT competition. Please take a look :)
