### ISSUE TITLE
lrat-check: Fails to verify large lrat files

### ISSUE THREAD

**Issue by marchartung** [marijnheule/drat-trim#23]
lrat-check seg faults on a LRAT proof generated through drat-trim from MapleLCMDistChronoBT from SAT Comp 18 on the benchmark queen13_13.col.13.cnf. The LRAT file is 8.7 GB. The error is caused by an integer overflow of tableAlloc in line 146. 

The quick fix is to change tableAlloc and tableSize to size_t. Also the realloc is not checked.

**Comment by marijnheule** [comment]
I expect that this is fixed with the bucket lookup. Let me know if you are still experiencing something along these lines. I also added realloc checks.
