### ISSUE TITLE
A small issue

### ISSUE THREAD

**Issue by DennisYurichev** [marijnheule/drat-trim#30]
Not sure if it is important or not.. but a strange warnings issued by drat-trim.
These CNF and PROOF files: https://yurichev.com/tmp/drat-trim-issue/

Running: ./drat-trim SAT_lib.factor.cnf SAT_lib.factor.proof

```
c turning on binary mode checking
c parsing input formula with 2949 variables and 16465 clauses
c WARNING: detected and deleted duplicate literal -1 at position 2 of line 16466
c WARNING: detected and deleted duplicate literal 1 at position 2 of line 16470
c WARNING: detected and deleted duplicate literal -1 at position 1 of line 16475
c WARNING: detected and deleted duplicate literal 1 at position 2 of line 16478
c finished parsing, read 7896429 bytes from proof file
c detected empty clause; start verification via backward checking
c 8629 of 16465 clauses in core
c 52635 of 294627 lemmas in core using 6846566 resolution steps
c 0 RAT lemmas in core; 33702 redundant literals in core lemmas
s VERIFIED
c verification time: 4.806 seconds
```

OK, but there are only 16466 lines in the SAT_lib.factor.cnf file.
drat-trim issues warnings about lines >=16470.

**Comment by krobelus** [comment]
> c parsing input formula with 2949 variables and 16465 clauses
> c WARNING: detected and deleted duplicate literal -1 at position 2 of line 16466
> c WARNING: detected and deleted duplicate literal 1 at position 2 of line 16470
> c WARNING: detected and deleted duplicate literal -1 at position 1 of line 16475
> c WARNING: detected and deleted duplicate literal 1 at position 2 of line 16478
> c finished parsing, read 7896429 bytes from proof file
> c detected empty clause; start verification via backward checking
> c 8629 of 16465 clauses in core
> c 52635 of 294627 lemmas in core using 6846566 resolution steps
> c 0 RAT lemmas in core; 33702 redundant literals in core lemmas
> s VERIFIED
> c verification time: 4.806 seconds
> ```
> 
> OK, but there are only 16466 lines in the SAT_lib.factor.cnf file.
> drat-trim issues warning about lines >=16470.

Right, that's another thing that's totally non-obvious for users,
but it makes sense when you think about how it's implemented.

drat-trim uses the same routine to read both the input formula and the
proof, and stores everything in a big clause database.  So the line number
is w.r.t. to a concatenation of formula + proof.
("line" doesn't actually mean ASCII line, but rather "clause/proof step").

The warnings stem from proof lemmas with duplicate literals.
Since you're using compressed (binary) DRAT, it's not so obvious, but
you can convert it to the text format, for example with bdrat2drat from
rate-proof-utils (see https://github.com/krobelus/rate)

	$ bdrat2drat < yurichev.com/tmp/drat-trim-issue/SAT_lib.factor.proof | head
	d -95 -1 -1 96 0
	d -95 -1 97 0
	d -95 -1 97 0
	95 -96 0
	d 95 1 1 -96 0
	95 -97 0
	d 95 1 -97 0
	95 -97 0
	d 95 1 -97 0
	d -1 -1 97 0

**Comment by DennisYurichev** [comment]
Ah, I see, thanks.

**Comment by marijnheule** [comment]
I agree that this is not very clear. I changed "line" to "proof line".
