### ISSUE TITLE
Trace check file contains clauses not in the original proof

### ISSUE THREAD

**Issue by hgvk94** [marijnheule/drat-trim#7]
In most of the instances, there seems to be clauses in the trace check file that are not in the proof ( neither in the lemmas nor in the formula ).

Here is what I did : 
I ran glucose 4.1 on an unsat formula (test.txt) and produced a proof (test-proof.txt)
I ran drat trim on the proof and generated the trace check output file (test-traceFile.txt)

I can find clauses like -233 244 -263 in the trace check file whereas I cannot find the clause neither in the proof produced by glucose nor in the cnf file. 

However, I can find a clause -233 244 -263 -261 in the proof which is very similar to this one. 

[test.txt](https://github.com/marijnheule/drat-trim/files/1713033/test.txt)

[test-proof.txt](https://github.com/marijnheule/drat-trim/files/1713036/test-proof.txt)

[test-traceFile.txt](https://github.com/marijnheule/drat-trim/files/1713037/test-traceFile.txt)

The formula is from SAT competition 2016. It was originally named modgen-n200-m90860q08c40-12992.cnf 
I find that this happens very often in other formulas as well.

**Comment by marijnheule** [comment]
Literals in lemmas (i.e., proof clauses) that were redundant during checking are removed. To turn this off, run the checker with the -R command line option.
